### PR TITLE
Setup repo

### PR DESCRIPTION
**Pull request by jacobvjk**
This PR:
- updates the .gitignore file
- adds GH actions via workflows for some basic sanity checks

### CODE REVIEW

**Comment by jdhoffa** [comment]
Hey @jacobvjk are you planning on setting up this repo as an R package? 
The workflows here (R CMD check) will only pass if the R package infrastructure is in place.

**Comment by jacobvjk** [comment]
@jdhoffa yea thanks for pointing out.. I'm not sure. tbh at this stage I don't see the benefit of making this a package. So will probably just close the PR.

**Comment by jdhoffa** [comment]
It depends what you're trying to do exactly, there is definitely a lot of convenience if you want to make use of automated tests etc., but it might be too much overhead. Really depends on the purpose of the repo.

**Comment by jacobvjk** [comment]
yes, I considered that. But still tbh I think it will remain super simple. Worst case I have to set it up another time, that's fine. For now there will probably not be any functions that need testing

**Pull request closed without merging**
